
# GET ALL MOVIES
# GET http://localhost:1234/movies 

# GET A MOVIE
# GET http://localhost:1234/movies/c8a7d63f-3b04-44d3-9d95-8782fd7dcfaf
# GET A GENRE
# GET http://localhost:1234/movies?genre=fantasy
# ADD A MOVIE
POST http://localhost:1234/movies
Content-Type: application/json

{
    "title": "La La Land",
    "year": 2016,
    "director": "Ryan Gosling",
    "duration": 128,
    "poster": "https://www.imdb.com/title/tt3783958/mediaviewer/rm4218189056/?ref_=tt_ov_i",
    "genre": [
      "Romantic"
    ],
    "rate": 10
}

# ACTUALIZAR UNA PARTE DE UNA PELICULA
# PATCH http://localhost:1234/movies/5ad1a235-0d9c-410a-b32b-220d91689a08
# Content-Type: application/json

# {
#     "id":"INCEPTION"
# }